name: 'IPFS Remote Pinning'
description: 'Pin your website to a IPFS Remote Pinning Service'
inputs:
  path_to_add:
    description: 'Directory path to add to IPFS'
    required: true
  endpoint:
    description: 'Url of API Endpoint'
    required: true
  access_token:
    description: 'Access Token for API Endpoint'
    required: true
  pin_name:
    description: 'Name of pin'
    required: false
outputs:
  cid:
    description: 'IPFS Content ID of the pinned file/directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    UPLOAD_PATH: ${{ inputs.path_to_add }}
    ENDPOINT: ${{ inputs.endpoint }}
    ACCESS_TOKEN: ${{ inputs.access_token }}
    NAME: ${{ inputs.pin_name }}
  